# Generated by Django 5.0.dev20230213052949 on 2023-02-18 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="choice",
            old_name="choise_text",
            new_name="choice_text",
        ),
    ]
